language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
install:
  # setup.py test (script) fetches all test_require files, thus no pip needed
  #- pip install --use-mirrors -r test-requirements.txt
  - pip install coveralls
script:
  #nosetests -v
  coverage run --source=lesscpy setup.py test
after_success:
  coveralls
